import { Dsa } from "@/types/Dsa";

export const _70Dsa: Dsa[] = [
  {
    category: "Arrays",
    title: "Contains Duplicate",
    url: "https://leetcode.com/problems/contains-duplicate",
    type: "Question",
  },
  {
    category: "Arrays",
    title: "Missing Number",
    url: "https://leetcode.com/problems/missing-number",
    type: "Question",
  },
  {
    category: "Arrays",
    title: "Find All Numbers Disappeared in an Array",
    url: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array",
    type: "Question",
  },
  {
    category: "Arrays",
    title: "Two Sum",
    url: "https://leetcode.com/problems/two-sum",
    type: "Question",
  },
  {
    category: "Arrays",
    title: "How Many Numbers Are Smaller Than the Current Number",
    url: "https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number",
    type: "Question",
  },
  {
    category: "Arrays",
    title: "Minimum Time Visiting All Points",
    url: "https://leetcode.com/problems/minimum-time-visiting-all-points",
    type: "Question",
  },
  {
    category: "Arrays",
    title: "Spiral Matrix",
    url: "https://leetcode.com/problems/spiral-matrix",
    type: "Question",
  },
  {
    category: "Arrays",
    title: "Number of Islands",
    url: "https://leetcode.com/problems/number-of-islands",
    type: "Question",
  },
  {
    category: "Arrays - Two Pointers",
    title: "Best Time to Buy and Sell Stock",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock",
    type: "Question",
  },
  {
    category: "Arrays - Two Pointers",
    title: "Squares of a Sorted Array",
    url: "https://leetcode.com/problems/squares-of-a-sorted-array",
    type: "Question",
  },
  {
    category: "Arrays - Two Pointers",
    title: "3Sum",
    url: "https://leetcode.com/problems/3sum",
    type: "Question",
  },
  {
    category: "Arrays - Two Pointers",
    title: "Longest Mountain in Array",
    url: "https://leetcode.com/problems/longest-mountain-in-array",
    type: "Question",
  },
  {
    category: "Arrays - Sliding Window",
    title: "Contains Duplicate II",
    url: "https://leetcode.com/problems/contains-duplicate-ii",
    type: "Question",
  },
  {
    category: "Arrays - Sliding Window",
    title: "Minimum Absolute Difference",
    url: "https://leetcode.com/problems/minimum-absolute-difference",
    type: "Question",
  },
  {
    category: "Arrays - Sliding Window",
    title: "Minimum Size Subarray Sum",
    url: "https://leetcode.com/problems/minimum-size-subarray-sum",
    type: "Question",
  },
  {
    category: "Bit Manipulation",
    title: "Single Number",
    url: "https://leetcode.com/problems/single-number",
    type: "Question",
  },
  {
    category: "Dynamic Programming",
    title: "Coin Change",
    url: "https://leetcode.com/problems/coin-change",
    type: "Question",
  },
  {
    category: "Dynamic Programming",
    title: "Climbing Stairs",
    url: "https://leetcode.com/problems/climbing-stairs",
    type: "Question",
  },
  {
    category: "Dynamic Programming",
    title: "Maximum Subarray",
    url: "https://leetcode.com/problems/maximum-subarray",
    type: "Question",
  },
  {
    category: "Dynamic Programming",
    title: "Counting Bits",
    url: "https://leetcode.com/problems/counting-bits",
    type: "Question",
  },
  {
    category: "Dynamic Programming",
    title: "Range Sum Query - Immutable",
    url: "https://leetcode.com/problems/range-sum-query---immutable",
    type: "Question",
  },
  {
    category: "Backtracking",
    title: "Letter Case Permutation",
    url: "https://leetcode.com/problems/letter-case-permutation",
    type: "Question",
  },
  {
    category: "Backtracking",
    title: "Subsets",
    url: "https://leetcode.com/problems/subsets",
    type: "Question",
  },
  {
    category: "Backtracking",
    title: "Combinations",
    url: "https://leetcode.com/problems/combinations",
    type: "Question",
  },
  {
    category: "Backtracking",
    title: "Permutations",
    url: "https://leetcode.com/problems/permutations",
    type: "Question",
  },
  {
    category: "Linked Lists",
    title: "Middle of Linked List",
    url: "https://leetcode.com/problems/middle-of-linked-list",
    type: "Question",
  },
  {
    category: "Linked Lists",
    title: "Linked List Cycle",
    url: "https://leetcode.com/problems/linked-list-cycle",
    type: "Question",
  },
  {
    category: "Linked Lists",
    title: "Reverse Linked List",
    url: "https://leetcode.com/problems/reverse-linked-list",
    type: "Question",
  },
  {
    category: "Linked Lists",
    title: "Remove Linked List Elements",
    url: "https://leetcode.com/problems/remove-linked-list-elements",
    type: "Question",
  },
  {
    category: "Linked Lists",
    title: "Reverse Linked List II",
    url: "https://leetcode.com/problems/reverse-linked-list-ii",
    type: "Question",
  },
  {
    category: "Linked Lists",
    title: "Palindrome Linked List",
    url: "https://leetcode.com/problems/palindrome-linked-list",
    type: "Question",
  },
  {
    category: "Linked Lists",
    title: "Merge Two Sorted Lists",
    url: "https://leetcode.com/problems/merge-two-sorted-lists",
    type: "Question",
  },
  {
    category: "Stacks",
    title: "Min Stack",
    url: "https://leetcode.com/problems/min-stack",
    type: "Question",
  },
  {
    category: "Stacks",
    title: "Valid Parentheses",
    url: "https://leetcode.com/problems/valid-parentheses",
    type: "Question",
  },
  {
    category: "Stacks",
    title: "Evaluate Reverse Polish Notation",
    url: "https://leetcode.com/problems/evaluate-reverse-polish-notation",
    type: "Question",
  },
  {
    category: "Stacks",
    title: "Stack Sorting",
    url: "https://leetcode.com/problems/stack-sorting",
    type: "Question",
  },
  {
    category: "Queues",
    title: "Implement Stack using Queues",
    url: "https://leetcode.com/problems/implement-stack-using-queues",
    type: "Question",
  },
  {
    category: "Queues",
    title: "Time Needed to Buy Tickets",
    url: "https://leetcode.com/problems/time-needed-to-buy-tickets",
    type: "Question",
  },
  {
    category: "Queues",
    title: "Reverse the First K Elements of a Queue",
    url: "https://leetcode.com/problems/reverse-the-first-k-elements-of-a-queue",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Average of Levels in Binary Tree",
    url: "https://leetcode.com/problems/average-of-levels-in-binary-tree",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Minimum Depth of Binary Tree",
    url: "https://leetcode.com/problems/minimum-depth-of-binary-tree",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Maximum Depth of Binary Tree",
    url: "https://leetcode.com/problems/maximum-depth-of-binary-tree",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Min/Max Value Binary Tree",
    url: "https://leetcode.com/problems/min/max-value-binary-tree",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Binary Tree Level Order Traversal",
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Same Tree",
    url: "https://leetcode.com/problems/same-tree",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Path Sum",
    url: "https://leetcode.com/problems/path-sum",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Diameter of a Binary Tree",
    url: "https://leetcode.com/problems/diameter-of-a-binary-tree",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Invert Binary Tree",
    url: "https://leetcode.com/problems/invert-binary-tree",
    type: "Question",
  },
  {
    category: "Binary Trees",
    title: "Lowest Common Ancestor of a Binary Tree",
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree",
    type: "Question",
  },
  {
    category: "Binary Search Trees",
    title: "Search in a Binary Search Tree",
    url: "https://leetcode.com/problems/search-in-a-binary-search-tree",
    type: "Question",
  },
  {
    category: "Binary Search Trees",
    title: "Insert into a Binary Search Tree",
    url: "https://leetcode.com/problems/insert-into-a-binary-search-tree",
    type: "Question",
  },
  {
    category: "Binary Search Trees",
    title: "Convert Sorted Array to Binary Search Tree",
    url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree",
    type: "Question",
  },
  {
    category: "Binary Search Trees",
    title: "Two Sum IV - Input is a BST",
    url: "https://leetcode.com/problems/two-sum-iv---input-is-a-bst",
    type: "Question",
  },
  {
    category: "Binary Search Trees",
    title: "Lowest Common Ancestor of a Binary Search Tree",
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree",
    type: "Question",
  },
  {
    category: "Binary Search Trees",
    title: "Minimum Absolute Difference in BST",
    url: "https://leetcode.com/problems/minimum-absolute-difference-in-bst",
    type: "Question",
  },
  {
    category: "Binary Search Trees",
    title: "Balance a Binary Search Tree",
    url: "https://leetcode.com/problems/balance-a-binary-search-tree",
    type: "Question",
  },
  {
    category: "Binary Search Trees",
    title: "Delete Node in a BST",
    url: "https://leetcode.com/problems/delete-node-in-a-bst",
    type: "Question",
  },
  {
    category: "Binary Search Trees",
    title: "Kth Smallest Element in a BST",
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst",
    type: "Question",
  },
  {
    category: "Heaps",
    title: "Kth Largest Element in an Array",
    url: "https://leetcode.com/problems/kth-largest-element-in-an-array",
    type: "Question",
  },
  {
    category: "Heaps",
    title: "K Closest Points to Origin",
    url: "https://leetcode.com/problems/k-closest-points-to-origin",
    type: "Question",
  },
  {
    category: "Heaps",
    title: "Top K Frequent Elements",
    url: "https://leetcode.com/problems/top-k-frequent-elements",
    type: "Question",
  },
  {
    category: "Heaps",
    title: "Task Scheduler",
    url: "https://leetcode.com/problems/task-scheduler",
    type: "Question",
  },
  {
    category: "Graphs",
    title: "Clone Graph",
    url: "https://leetcode.com/problems/clone-graph",
    type: "Question",
  },
  {
    category: "Graphs",
    title: "Cheapest Flights Within K Stops",
    url: "https://leetcode.com/problems/cheapest-flights-within-k-stops",
    type: "Question",
  },
  {
    category: "Graphs",
    title: "Course Schedule",
    url: "https://leetcode.com/problems/course-schedule",
    type: "Question",
  },
];
