import { Dsa } from "@/types/Dsa";

export const dsaSheet: Dsa[] = [
  {
    category: "Introduction",
    title: "Algorithm Analysis",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/analysis-of-algorithms/",
  },
  {
    category: "Introduction",
    title: "Asymptotic Complexity",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/asymptotic-notation-and-analysis-based-on-input-size-of-algorithms/",
  },
  {
    category: "Introduction",
    title: "Growth Order",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/gate/order-o-f-growth/",
  },
  {
    category: "Introduction",
    title: "Best, Average, and Worst Cases",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/worst-average-and-best-case-analysis-of-algorithms/",
  },
  {
    category: "Introduction",
    title: "Asymptotic Notation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/types-of-asymptotic-notations-in-complexity-analysis-of-algorithms/",
  },
  {
    category: "Introduction",
    title: "Big O Notation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/analysis-algorithms-big-o-analysis/",
  },
  {
    category: "Introduction",
    title: "Omega Notation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/analysis-of-algorithms-big-omega-notation/",
  },
  {
    category: "Introduction",
    title: "Theta Notation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/analysis-of-algorithms-big-theta-notation/",
  },
  {
    category: "Introduction",
    title: "Analysis of Common Loops",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/how-to-analyse-loops-for-complexity-analysis-of-algorithms/",
  },
  {
    category: "Introduction",
    title: "Analysis of Multiple Loops",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/how-to-analyse-loops-for-complexity-analysis-of-algorithms/",
  },
  {
    category: "Introduction",
    title: "Analysis of Recursion",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/how-to-analyse-complexity-of-recurrence-relation/",
  },
  {
    category: "Introduction",
    title: "Recursion Tree Method of Solving Recurrences",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/how-to-solve-time-complexity-recurrence-relations-using-recursion-tree-method/",
  },
  {
    category: "Introduction",
    title: "More Example Recurrences",
    type: "Explanation",
    url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20230620154724/DSA-to-development.pdf",
  },
  {
    category: "Introduction",
    title: "Upper Bound Using Recursion Tree Method",
    type: "Explanation",
    url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20230620154724/DSA-to-development.pdf",
  },
  {
    category: "Introduction",
    title: "Space Complexity",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/g-fact-86/",
  },
  {
    category: "Mathematics",
    title: "Count Digits",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/program-count-digits-integer-3-different-methods/",
  },
  {
    category: "Mathematics",
    title: "Palindrome Number",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/check-if-a-number-is-palindrome/",
  },
  {
    category: "Mathematics",
    title: "Factorial of a Number",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/program-for-factorial-of-a-number/",
  },
  {
    category: "Mathematics",
    title: "Trailing Zeros in a Factorial",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/count-trailing-zeroes-factorial-number/",
  },
  {
    category: "Mathematics",
    title: "GCD/HCF of 2 numbers",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/program-to-find-gcd-or-hcf-of-two-numbers/",
  },
  {
    category: "Mathematics",
    title: "LCM of 2 numbers",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/program-to-find-lcm-of-two-numbers/",
  },
  {
    category: "Mathematics",
    title: "Check for prime",
    type: "Question",
    url: "https://www.geeksforgeeks.org/check-if-a-number-is-prime-or-not/",
  },
  {
    category: "Mathematics",
    title: "Prime Factors",
    type: "Question",
    url: "https://www.geeksforgeeks.org/print-all-prime-factors-of-a-given-number/",
  },
  {
    category: "Mathematics",
    title: "All Divisors of a Number",
    type: "Question",
    url: "https://www.geeksforgeeks.org/find-divisors-natural-number-set-1/",
  },
  {
    category: "Mathematics",
    title: "Sieve of Eratosthenes",
    type: "Question",
    url: "https://www.geeksforgeeks.org/sieve-of-eratosthenes/",
  },
  {
    category: "Mathematics",
    title: "Computing pow(x, n)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/write-a-c-program-to-calculate-powxn/",
  },
  {
    category: "Mathematics",
    title: "Itertive Power (Binary Exponentiation)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/binary-exponentiation-fast-pow-algorithm/",
  },
  {
    category: "Bit Magic",
    title: "Bitwise Operator in CPP",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp/cpp-bitwise-operators/",
  },
  {
    category: "Bit Magic",
    title: "Check if Kth bit is set or not",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/check-whether-k-th-bit-set-not/",
  },
  {
    category: "Bit Magic",
    title: "Count Set Bits",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/count-set-bits-in-an-integer/",
  },
  {
    category: "Bit Magic",
    title: "Power of Two",
    type: "Question",
    url: "https://www.geeksforgeeks.org/c/c-program-to-find-whether-a-no-is-power-of-two/",
  },
  {
    category: "Bit Magic",
    title: "Only Odd Occurring Number",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-the-number-occurring-odd-number-of-times/",
  },
  {
    category: "Bit Magic",
    title: "Two Odd Appearing Numbers",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-the-two-numbers-with-odd-occurences-in-an-unsorted-array/",
  },
  {
    category: "Bit Magic",
    title: "Power Set using Bitwise Operator",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/power-set/",
  },
  {
    category: "Recursion",
    title: "Recursion Introduction",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/what-is-recursion/",
  },
  {
    category: "Recursion",
    title: "Application of Recursion",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/javascript/applications-of-recursion-in-javascript/",
  },
  {
    category: "Recursion",
    title: "Recursion Output Practice",
    type: "Question",
    url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20230620154724/DSA-to-development.pdf",
  },
  {
    category: "Recursion",
    title: "Print n to 1 using Recursion",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/print-n-to-1-without-loop/",
  },
  {
    category: "Recursion",
    title: "Print 1 to n using Recursion",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/print-1-to-n-without-using-loops/",
  },
  {
    category: "Recursion",
    title: "Tail Recursion",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/tail-recursion/",
  },
  {
    category: "Recursion",
    title: "Writing Base Cases in Recursion",
    type: "Question",
    url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20230620154724/DSA-to-development.pdf",
  },
  {
    category: "Recursion",
    title: "Sum of Natural Numbers using Recursion",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/program-find-sum-first-n-natural-numbers/",
  },
  {
    category: "Recursion",
    title: "Palindrome Check using Recursion",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/recursive-function-check-string-palindrome/",
  },
  {
    category: "Recursion",
    title: "Sum of Digits using Recursion",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/sum-digit-number-using-recursion/",
  },
  {
    category: "Recursion",
    title: "Rope Cutting Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/maximum-number-segments-lengths-b-c/",
  },
  {
    category: "Recursion",
    title: "Generate Subsets",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/recursive-program-to-generate-power-set/",
  },
  {
    category: "Recursion",
    title: "Tower of Hanoi",
    type: "Question",
    url: "https://www.geeksforgeeks.org/c/c-program-for-tower-of-hanoi-2/",
  },
  {
    category: "Recursion",
    title: "Josephus Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/josephus-problem/",
  },
  {
    category: "Recursion",
    title: "Subset Sum Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/subset-sum-problem-dp-25/",
  },
  {
    category: "Recursion",
    title: "Print all Permutations of a String",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/print-all-permutations-of-a-string-in-java/",
  },
  {
    category: "Arrays",
    title: "Array Data Structure",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/array-data-structure-guide/",
  },
  {
    category: "Arrays",
    title: "Array Types",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/types-of-arrays/",
  },
  {
    category: "Arrays",
    title: "Vectors in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp/vector-in-cpp-stl/",
  },
  {
    category: "Arrays",
    title: "Operations on Array",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/introduction-to-dsa/",
  },
  {
    category: "Arrays",
    title: "Largest Element in the Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/program-to-find-largest-element-in-an-array/",
  },
  {
    category: "Arrays",
    title: "Second Largest Element in the Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-second-largest-element-array/",
  },
  {
    category: "Arrays",
    title: "Check if an array is sorted",
    type: "Question",
    url: "https://www.geeksforgeeks.org/program-to-check-if-an-array-is-sorted-or-not/",
  },
  {
    category: "Arrays",
    title: "Reverse on Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/",
  },
  {
    category: "Arrays",
    title: "Remove Duplicated from a Sorted Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/remove-duplicates-from-a-sorted-array/",
  },
  {
    category: "Arrays",
    title: "Move all Zeroes to End",
    type: "Question",
    url: "https://www.geeksforgeeks.org/move-all-zeroes-to-end-of-array-using-two-pointers/",
  },
  {
    category: "Arrays",
    title: "Left Rotate on Array by One",
    type: "Question",
    url: "https://www.geeksforgeeks.org/left-rotate-an-array-by-one/",
  },
  {
    category: "Arrays",
    title: "Left Rotate on Array by d",
    type: "Question",
    url: "https://www.geeksforgeeks.org/left-rotate-an-array-by-d-positions/",
  },
  {
    category: "Arrays",
    title: "Leaders in an Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/leaders-in-an-array/",
  },
  {
    category: "Arrays",
    title: "Maximum Difference Problem with Order",
    type: "Question",
    url: "https://www.geeksforgeeks.org/maximum-difference-between-two-elements-such-that-larger-element-appears-after-the-smaller-number/",
  },
  {
    category: "Arrays",
    title: "Frequencies in a Sorted Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/count-frequencies-of-array-elements/",
  },
  {
    category: "Arrays",
    title: "Stock Buy and Sell (Naive)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/stock-buy-sell/",
  },
  {
    category: "Arrays",
    title: "Stock Buy and Sell (Efficient)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/stock-buy-sell/",
  },
  {
    category: "Arrays",
    title: "Trapping Rain Water",
    type: "Question",
    url: "https://www.geeksforgeeks.org/trapping-rain-water/",
  },
  {
    category: "Arrays",
    title: "Maximum Consecutive 1s in a Binary Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/maximum-consecutive-ones-or-zeroes-in-a-binary-array/",
  },
  {
    category: "Arrays",
    title: "Maximum Sum Subarray",
    type: "Question",
    url: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
  },
  {
    category: "Arrays",
    title: "Maximum Length Even-Odd Subarray",
    type: "Question",
    url: "https://www.geeksforgeeks.org/maximum-length-even-odd-subarray/",
  },
  {
    category: "Arrays",
    title: "Maxium Circular Subarray Sum",
    type: "Question",
    url: "https://www.geeksforgeeks.org/maximum-contiguous-circular-sum/",
  },
  {
    category: "Arrays",
    title: "Majority Element",
    type: "Question",
    url: "https://www.geeksforgeeks.org/majority-element/",
  },
  {
    category: "Arrays",
    title: "Minimum Group Flips to make same",
    type: "Question",
    url: "https://www.geeksforgeeks.org/minimum-group-flips-to-make-binary-array-elements-same/",
  },
  {
    category: "Arrays",
    title: "Window Sliding Technique",
    type: "Question",
    url: "https://www.geeksforgeeks.org/window-sliding-technique/",
  },
  {
    category: "Arrays",
    title: "Subarray with Given Sum",
    type: "Question",
    url: "https://www.geeksforgeeks.org/find-subarray-with-given-sum/",
  },
  {
    category: "Arrays",
    title: "Prefix Sum",
    type: "Question",
    url: "https://www.geeksforgeeks.org/prefix-sum-array-implementation-applications-competitive-programming/",
  },
  {
    category: "Arrays",
    title: "Weighted Prefix Sum",
    type: "Question",
    url: "https://www.geeksforgeeks.org/prefix-sum-array-implementation-applications-competitive-programming/",
  },
  {
    category: "Arrays",
    title: "Equilbrium Point",
    type: "Question",
    url: "https://www.geeksforgeeks.org/equilibrium-index-of-an-array/",
  },
  {
    category: "Arrays",
    title: "Maximum Appearing Element in Ranges",
    type: "Question",
    url: "https://www.geeksforgeeks.org/maximum-appearing-element-in-ranges/",
  },

  {
    category: "Searching",
    title: "Binary Search",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-search/",
  },
  {
    category: "Searching",
    title: "Analysis of Binary Search",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/time-complexity-of-binary-search/",
  },
  {
    category: "Searching",
    title: "Index of First and Last Occurence",
    type: "Question",
    url: "https://www.geeksforgeeks.org/find-first-and-last-positions-of-an-element-in-a-sorted-array/",
  },
  {
    category: "Searching",
    title: "Count 1s in a Sorted Binary Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/count-1s-sorted-binary-array/",
  },
  {
    category: "Searching",
    title: "Square Root",
    type: "Question",
    url: "https://www.geeksforgeeks.org/square-root-of-an-integer/",
  },
  {
    category: "Searching",
    title: "Search in an Infinite Sorted Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-infinite-array/",
  },
  {
    category: "Searching",
    title: "Search in a Sorted Rotated Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
  },
  {
    category: "Searching",
    title: "Find a Peak Element",
    type: "Question",
    url: "https://www.geeksforgeeks.org/find-a-peak-element/",
  },
  {
    category: "Searching",
    title: "Two Pointer Approach",
    type: "Question",
    url: "https://www.geeksforgeeks.org/two-pointer-technique/",
  },
  {
    category: "Searching",
    title: "Triplet in a Sorted Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/find-a-triplet-that-sum-to-a-given-value/",
  },
  {
    category: "Searching",
    title: "Median of Two Sorted Arrays",
    type: "Question",
    url: "https://www.geeksforgeeks.org/median-of-two-sorted-arrays-of-different-sizes/",
  },
  {
    category: "Searching",
    title: "Repeating Element - 1",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-first-repeating-element-array-integers/",
  },
  {
    category: "Searching",
    title: "Repeating Element - 2",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-repetitive-element-1-n-1/",
  },
  {
    category: "Searching",
    title: "Allocate Minimum No. of Pages",
    type: "Question",
    url: "https://www.geeksforgeeks.org/allocate-minimum-number-pages/",
  },

  {
    category: "Sorting",
    title: "Sort in C++ STL",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/sort-c-stl/",
  },
  {
    category: "Sorting",
    title: "Stability in Sorting Algorithms",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/stability-in-sorting-algorithms/",
  },
  {
    category: "Sorting",
    title: "Bubble Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/bubble-sort/",
  },
  {
    category: "Sorting",
    title: "Selection Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/selection-sort/",
  },
  {
    category: "Sorting",
    title: "Insertion Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/insertion-sort/",
  },
  {
    category: "Sorting",
    title: "Merge Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/merge-sort/",
  },
  {
    category: "Sorting",
    title: "Intersection of Two Sorted Arrays",
    type: "Question",
    url: "https://www.geeksforgeeks.org/intersection-of-two-sorted-arrays/",
  },
  {
    category: "Sorting",
    title: "Unions of Two Sorted Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/union-of-two-sorted-arrays/",
  },
  {
    category: "Sorting",
    title: "Count Inversions in an Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/counting-inversions/",
  },
  {
    category: "Sorting",
    title: "Quick Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/quick-sort/",
  },
  {
    category: "Sorting",
    title: "Kth Smallest Element",
    type: "Question",
    url: "https://www.geeksforgeeks.org/kth-smallestlargest-element-unsorted-array/",
  },
  {
    category: "Sorting",
    title: "Minimum Difference in an Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/find-minimum-difference-between-any-two-elements/",
  },
  {
    category: "Sorting",
    title: "Chocolate Distribution in an Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/chocolate-distribution-problem/",
  },
  {
    category: "Sorting",
    title: "Sort an Array with Two Types",
    type: "Question",
    url: "https://www.geeksforgeeks.org/sort-array-two-types-elements/",
  },
  {
    category: "Sorting",
    title: "Sort an Array with Three Types",
    type: "Question",
    url: "https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/",
  },
  {
    category: "Sorting",
    title: "Merge Overlapping Intervals",
    type: "Question",
    url: "https://www.geeksforgeeks.org/merging-intervals/",
  },
  {
    category: "Sorting",
    title: "Meeting the Maximum Guests",
    type: "Question",
    url: "https://www.geeksforgeeks.org/maximum-number-of-guests-at-a-party/",
  },
  {
    category: "Sorting",
    title: "Cycle Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/cycle-sort/",
  },
  {
    category: "Sorting",
    title: "Heap Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/heap-sort/",
  },
  {
    category: "Sorting",
    title: "Counting Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/counting-sort/",
  },
  {
    category: "Sorting",
    title: "Radix Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/radix-sort/",
  },
  {
    category: "Sorting",
    title: "Bucket Sort",
    type: "Question",
    url: "https://www.geeksforgeeks.org/bucket-sort-2/",
  },
  {
    category: "Sorting",
    title: "Overview of Sorting Algorithms",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/sorting-algorithms/",
  },

  {
    category: "Matrix",
    title: "Multidimentional Array",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/multidimensional-arrays-c-cpp/",
  },
  {
    category: "Matrix",
    title: "Passing 2D arrays as arguments",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/passing-a-2d-array-to-a-c-function/",
  },
  {
    category: "Matrix",
    title: "Matrix in Snake Pattern",
    type: "Question",
    url: "https://www.geeksforgeeks.org/print-matrix-snake-pattern/",
  },
  {
    category: "Matrix",
    title: "Matrix Boundary Traversal",
    type: "Question",
    url: "https://www.geeksforgeeks.org/boundary-elements-of-a-matrix/",
  },
  {
    category: "Matrix",
    title: "Transpose of a Matrix",
    type: "Question",
    url: "https://www.geeksforgeeks.org/program-to-find-transpose-of-a-matrix/",
  },
  {
    category: "Matrix",
    title: "Rotate Matrix Anti-clockwise by 90 degree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/rotate-a-matrix-by-90-degree-in-anticlockwise-direction-without-using-any-extra-space/",
  },
  {
    category: "Matrix",
    title: "Spiral Traversal of a Matrix",
    type: "Question",
    url: "https://www.geeksforgeeks.org/print-a-given-matrix-in-spiral-form/",
  },
  {
    category: "Matrix",
    title: "Search in Row-wise and Column-wise Sorted Matrix",
    type: "Question",
    url: "https://www.geeksforgeeks.org/search-in-row-wise-and-column-wise-sorted-matrix/",
  },
  {
    category: "Matrix",
    title: "Median of Row-wise Sorted Matrix",
    type: "Question",
    url: "https://www.geeksforgeeks.org/median-in-a-row-wise-sorted-matrix/",
  },

  {
    category: "Hashing",
    title: "Introduction to Hashing",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/introduction-to-hashing-2/",
  },
  {
    category: "Hashing",
    title: "Applications of Hashing",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/applications-of-hashing/",
  },
  {
    category: "Hashing",
    title: "Direct Address Table",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/direct-address-table/",
  },
  {
    category: "Hashing",
    title: "Hashing Functions",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/hashing-set-1-introduction/",
  },
  {
    category: "Hashing",
    title: "Collision Handling",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/collision-resolution-techniques-in-hashing/",
  },
  {
    category: "Hashing",
    title: "Chaining",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/hashing-set-2-separate-chaining/",
  },
  {
    category: "Hashing",
    title: "Implmentation of Chaining",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/separate-chaining-collision-handling-technique-in-hashing/",
  },
  {
    category: "Hashing",
    title: "Open Addressing",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/hashing-set-3-open-addressing/",
  },
  {
    category: "Hashing",
    title: "Double Hashing",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/double-hashing/",
  },
  {
    category: "Hashing",
    title: "Implementation of Open Addressing",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/hashing-set-3-open-addressing/",
  },
  {
    category: "Hashing",
    title: "Chaining vs Open Addressing",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/advantages-and-disadvantages-of-open-addressing-and-separate-chaining/",
  },
  {
    category: "Hashing",
    title: "unordered_set in C++ STL",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/unordered_set-in-cpp-stl/",
  },
  {
    category: "Hashing",
    title: "unordered_map in C++ STL",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/unordered_map-in-cpp-stl/",
  },
  {
    category: "Hashing",
    title: "Count Distinct Elements",
    type: "Question",
    url: "https://www.geeksforgeeks.org/count-distinct-elements-in-an-array/",
  },
  {
    category: "Hashing",
    title: "Frequencies of Array Elements",
    type: "Question",
    url: "https://www.geeksforgeeks.org/counting-frequencies-of-array-elements/",
  },
  {
    category: "Hashing",
    title: "Intersection of Two Arrays",
    type: "Question",
    url: "https://www.geeksforgeeks.org/intersection-of-two-arrays/",
  },
  {
    category: "Hashing",
    title: "Union of Two Unsorted Arrays",
    type: "Question",
    url: "https://www.geeksforgeeks.org/union-of-two-unsorted-arrays/",
  },
  {
    category: "Hashing",
    title: "Pair with given sum in Unsorted Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/find-a-pair-with-the-given-sum-in-an-array/",
  },
  {
    category: "Hashing",
    title: "Subbarray with 0 sum",
    type: "Question",
    url: "https://www.geeksforgeeks.org/find-if-there-is-a-subarray-with-0-sum/",
  },
  {
    category: "Hashing",
    title: "Subarray with given sum",
    type: "Question",
    url: "https://www.geeksforgeeks.org/find-subarray-with-given-sum-in-array-of-integers/",
  },
  {
    category: "Hashing",
    title: "Longest Subbarray with given sum",
    type: "Question",
    url: "https://www.geeksforgeeks.org/longest-sub-array-sum-k/",
  },
  {
    category: "Hashing",
    title: "Longest Subbarray with equal numbers if 0s and 1s",
    type: "Question",
    url: "https://www.geeksforgeeks.org/largest-subarray-with-equal-number-of-0s-and-1s/",
  },
  {
    category: "Hashing",
    title: "Longest Common Span with same sum in 2 arrays",
    type: "Question",
    url: "https://www.geeksforgeeks.org/longest-span-sum-two-binary-arrays/",
  },
  {
    category: "Hashing",
    title: "Longest Consequtive Subsequence",
    type: "Question",
    url: "https://www.geeksforgeeks.org/longest-consecutive-subsequence/",
  },
  {
    category: "Hashing",
    title: "Count Distinct Elements in Every Window",
    type: "Question",
    url: "https://www.geeksforgeeks.org/count-distinct-elements-in-every-window-of-size-k/",
  },
  {
    category: "Hashing",
    title: "More than n/k occureneces (O(nlogn))",
    type: "Question",
    url: "https://www.geeksforgeeks.org/count-elements-with-frequencies-greater-than-nk/",
  },
  {
    category: "Hashing",
    title: "More than n/k occureneces (O(nk))",
    type: "Question",
    url: "https://www.geeksforgeeks.org/count-elements-with-frequencies-greater-than-nk/",
  },

  {
    category: "String",
    title: "Introduction to String",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/string-data-structure/",
  },
  {
    category: "String",
    title: "Strings in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp-strings/",
  },
  {
    category: "String",
    title: "Palindrome Check using Recursion",
    type: "Question",
    url: "https://www.geeksforgeeks.org/check-string-palindrome-recursive-method/",
  },
  {
    category: "String",
    title: "Check if a string is subsequence of other",
    type: "Question",
    url: "https://www.geeksforgeeks.org/check-if-a-string-is-subsequence-of-another/",
  },
  {
    category: "String",
    title: "Check for Anagram",
    type: "Question",
    url: "https://www.geeksforgeeks.org/check-whether-two-strings-are-anagram-of-each-other/",
  },
  {
    category: "String",
    title: "Leftmost Repeating Character",
    type: "Question",
    url: "https://www.geeksforgeeks.org/leftmost-repeating-character/",
  },
  {
    category: "String",
    title: "Leftmost Non-Repeating Character",
    type: "Question",
    url: "https://www.geeksforgeeks.org/leftmost-non-repeating-character/",
  },
  {
    category: "String",
    title: "Reverse Words in a String",
    type: "Question",
    url: "https://www.geeksforgeeks.org/reverse-words-in-a-given-string/",
  },
  {
    category: "String",
    title: "Overview of Pattern Searching",
    type: "Question",
    url: "https://www.geeksforgeeks.org/pattern-searching/",
  },
  {
    category: "String",
    title: "Naive Pattern Searching",
    type: "Question",
    url: "https://www.geeksforgeeks.org/naive-pattern-searching/",
  },
  {
    category: "String",
    title: "Improved Naive Pattern Searching for Distinct",
    type: "Question",
    url: "https://www.geeksforgeeks.org/improved-naive-algorithm-for-pattern-searching/",
  },
  {
    category: "String",
    title: "Robin Karp Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/",
  },
  {
    category: "String",
    title: "KMP Algorithm (P1: Constructing LPS)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/preprocess-pattern-kmp-algorithm/",
  },
  {
    category: "String",
    title: "KMP Algorithm (P2: Complete Algorithm)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/kmp-algorithm-for-pattern-searching/",
  },
  {
    category: "String",
    title: "Check for Rotation",
    type: "Question",
    url: "https://www.geeksforgeeks.org/check-if-a-string-is-rotation-of-another/",
  },
  {
    category: "String",
    title: "Anagram Search",
    type: "Question",
    url: "https://www.geeksforgeeks.org/anagram-substring-search-search-permutations/",
  },
  {
    category: "String",
    title: "Lexicographic Rank of a String",
    type: "Question",
    url: "https://www.geeksforgeeks.org/lexicographic-rank-of-a-string/",
  },
  {
    category: "String",
    title: "Longest Substring with Distinct Character",
    type: "Question",
    url: "https://www.geeksforgeeks.org/length-of-the-longest-substring-without-repeating-characters/",
  },

  {
    category: "Linked List",
    title: "Problems with Array Data Structure",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/linked-list-data-structure/",
  },
  {
    category: "Linked List",
    title: "Singly Linked List Implementation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/singly-linked-list-tutorial/",
  },
  {
    category: "Linked List",
    title: "Traversing a Singly Linked List in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/traversal-of-singly-linked-list/",
  },
  {
    category: "Linked List",
    title: "Recursive Traversal of Single Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/traversal-of-singly-linked-list/",
  },
  {
    category: "Linked List",
    title: "Insert at Beginning of Singly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/insert-a-node-at-front-beginning-of-a-linked-list/",
  },
  {
    category: "Linked List",
    title: "Insert at the End of Singly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp/cpp-linked-list/",
  },
  {
    category: "Linked List",
    title: "Delete First Node in a Singly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/remove-first-node-of-the-linked-list/",
  },
  {
    category: "Linked List",
    title: "Delete Last Node in Singly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/remove-last-node-of-the-linked-list/",
  },
  {
    category: "Linked List",
    title: "Insert at given position in a Singly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp/cpp-linked-list/",
  },
  {
    category: "Linked List",
    title: "Search in a Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/search-an-element-in-a-linked-list/",
  },
  {
    category: "Linked List",
    title: "Doubly Linked List Implementation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/doubly-linked-list/",
  },
  {
    category: "Linked List",
    title: "Singly v/s Doubly Linked List (Advantages and Disadvantages)",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/doubly-linked-list/",
  },
  {
    category: "Linked List",
    title: "Insert at Beginning of Doubly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/doubly-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Insert at End of Doubly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/doubly-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Delete Head of a Doubly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/doubly-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Delete Last Node in Doubly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/doubly-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Circular Linked List Implementation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/python/circular-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Circular Linked List (Advantages and Disadvantages)",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/python/circular-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Insert at Beginning of Circular Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/python/circular-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Insert at the End of Circular Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/python/circular-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Delete Head of a Circular Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/python/circular-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Delete Kth Node from a Circular Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/python/circular-linked-list-in-python/",
  },
  {
    category: "Linked List",
    title: "Circular Doubly Linked List",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/insertion-in-doubly-circular-linked-list/",
  },
  {
    category: "Linked List",
    title: "Sorted Insert in a Linked List",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/given-a-linked-list-which-is-sorted-how-will-you-insert-in-sorted-way/",
  },
  {
    category: "Linked List",
    title: "Middle of a Linked List",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/write-a-c-function-to-print-the-middle-of-the-linked-list/",
  },
  {
    category: "Linked List",
    title: "Nth Node from end of a Linked List",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-nth-node-from-end-of-linked-list/",
  },
  {
    category: "Linked List",
    title: "Reverse a Linked Lists",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/reverse-a-linked-list/",
  },
  {
    category: "Linked List",
    title: "Remove Duplicate from a Sorted Singly Linked List",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/remove-duplicates-from-a-sorted-linked-list/",
  },
  {
    category: "Linked List",
    title: "Detect Loop",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/detect-loop-in-linked-list/",
  },
  {
    category: "Linked List",
    title: "Detect Loop using Floyed's Cycle Detection",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/detect-loop-in-linked-list/",
  },
  {
    category: "Linked List",
    title: "Detect and Remove Loop in a Linked List",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/detect-and-remove-loop-in-a-linked-list/",
  },
  {
    category: "Linked List",
    title: "Delete a node with only pointer given to it",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/delete-without-head-pointer/",
  },
  {
    category: "Linked List",
    title: "Segregate Even and Odd Nodes in C++",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/segregate-even-and-odd-nodes-in-a-linked-list/",
  },
  {
    category: "Linked List",
    title: "Intersection Point of Two Linked List",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/write-a-function-to-get-the-intersection-point-of-two-linked-lists/",
  },
  {
    category: "Linked List",
    title: "Pairwise Swap Nodes of Linked List in C++",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/pairwise-swap-elements-of-a-linked-list/",
  },
  {
    category: "Linked List",
    title: "Clone a Linked List with Random Pointer in C++",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/clone-linked-list-next-random-pointer-o1-space/",
  },
  {
    category: "Linked List",
    title: "LRU Cache Design",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/lru-cache-implementation/",
  },
  {
    category: "Linked List",
    title: "Merge Two Sorted Linked List",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/merge-two-sorted-linked-lists/",
  },
  {
    category: "Linked List",
    title: "Palindrome Linked List",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/function-to-check-if-a-singly-linked-list-is-palindrome/",
  },
  {
    category: "Stack",
    title: "Stack Data Structure",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/stack-data-structure/",
  },
  {
    category: "Stack",
    title: "Array Implementation of Stack in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp/cpp-program-to-implement-stack-using-array/",
  },
  {
    category: "Stack",
    title: "Linked List Implementation of Stack in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/implement-a-stack-using-singly-linked-list/",
  },
  {
    category: "Stack",
    title: "Applications of Stack",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/applications-advantages-and-disadvantages-of-stack/",
  },
  {
    category: "Stack",
    title: "Stack in C++ STL",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp/stack-in-cpp-stl/",
  },
  {
    category: "Stack",
    title: "Balanced Parenthesis",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/check-for-balanced-parentheses-in-an-expression/",
  },
  {
    category: "Stack",
    title: "Implement Two Stacks in an Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/implement-two-stacks-in-an-array/",
  },
  {
    category: "Stack",
    title: "Implement K Stacks in an Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/efficiently-implement-k-stacks-single-array/",
  },
  {
    category: "Stack",
    title: "Stack Span Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/the-stock-span-problem/",
  },
  {
    category: "Stack",
    title: "Previous Greater Element",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/previous-greater-element/",
  },
  {
    category: "Stack",
    title: "Next Greater Element",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/next-greater-element/",
  },
  {
    category: "Stack",
    title: "Largest Rectangular Area in Histogram",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/largest-rectangle-under-histogram/",
  },
  {
    category: "Stack",
    title: "Largest Rectangle with all 1s",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/maximum-size-rectangle-binary-sub-matrix-1s/",
  },
  {
    category: "Stack",
    title: "Stack with getMin() in O(1)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/design-a-stack-that-supports-getmin-in-o1-time-and-o1-extra-space/",
  },
  {
    category: "Stack",
    title: "Infix, Prefix and Postfix",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/stack-set-2-infix-to-postfix/",
  },
  {
    category: "Queue",
    title: "Queue Data Structure",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/queue-data-structure/",
  },
  {
    category: "Queue",
    title: "Applications of Queue",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/applications-of-queue-data-structure/",
  },
  {
    category: "Queue",
    title: "Array Implementation of Queue in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/introduction-and-array-implementation-of-queue/",
  },
  {
    category: "Queue",
    title: "Linked List Implemention of Queue in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp/cpp-program-to-implement-queue-using-linked-list/",
  },
  {
    category: "Queue",
    title: "Queue in C++ STL",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp/queue-cpp-stl/",
  },
  {
    category: "Queue",
    title: "Implmenting Stack using Queue",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/implement-stack-using-queue/",
  },
  {
    category: "Queue",
    title: "Reversing a Queue",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/reverse-a-queue/",
  },
  {
    category: "Queue",
    title: "Generate numbers with given digits",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/generate-binary-numbers-1-to-n/",
  },
  {
    category: "Deque",
    title: "Deque Data Structure",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/deque-data-structure/",
  },
  {
    category: "Deque",
    title: "Applications of Deque",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/applications-advantages-and-disadvantages-of-deque/",
  },
  {
    category: "Deque",
    title: "Array Implmentation of Deque in C++",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/implementation-of-deque-using-array-simple/",
  },
  {
    category: "Deque",
    title: "Deque in C++ STL",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/cpp/deque-cpp-stl/",
  },
  {
    category: "Deque",
    title: "Data Structure with min/max operation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/design-a-queue-data-structure-to-get-minimum-or-maximum-in-o1-time/",
  },
  {
    category: "Deque",
    title: "Maximums of all subarrays of size k",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/",
  },
  {
    category: "Deque",
    title: "First Circular Tour",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-a-tour-that-visits-all-stations-circle/",
  },
  {
    category: "Tree",
    title: "Tree Data Structure",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/tree-data-structure/",
  },
  {
    category: "Tree",
    title: "Applications of Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/applications-of-tree-data-structure/",
  },
  {
    category: "Tree",
    title: "Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/binary-tree-data-structure/",
  },
  {
    category: "Tree",
    title: "Tree Traversal",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/tree-traversals-inorder-preorder-and-postorder/",
  },
  {
    category: "Tree",
    title: "Implementation of Traversals",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/implement-tree-traversal/",
  },
  {
    category: "Tree",
    title: "Height of a Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/write-a-c-program-to-find-the-maximum-depth-or-height-of-a-tree/",
  },
  {
    category: "Tree",
    title: "Print nodes at K distance",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/print-nodes-at-k-distance-from-root/",
  },
  {
    category: "Tree",
    title: "Size of a Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/write-a-c-program-to-calculate-size-of-a-tree/",
  },
  {
    category: "Tree",
    title: "Maximum in a Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-maximum-element-in-binary-tree/",
  },
  {
    category: "Tree",
    title: "Print Left View of a Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/print-left-view-of-a-binary-tree/",
  },
  {
    category: "Tree",
    title: "Children Sum Property",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/children-sum-parent/",
  },
  {
    category: "Tree",
    title: "Check for Balanced Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/check-if-a-binary-tree-is-balanced/",
  },
  {
    category: "Tree",
    title: "Maximum Width of Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/maximum-width-of-a-binary-tree/",
  },
  {
    category: "Tree",
    title: "Convert a Binary Tree to DLL",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/convert-given-binary-tree-doubly-linked-list/",
  },
  {
    category: "Tree",
    title: "Convert Binary Tree from Inorder and Preorder",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/construct-tree-from-inorder-preorder/",
  },
  {
    category: "Tree",
    title: "Tree Traversal in Spiral Form",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/level-order-traversal-in-spiral-form/",
  },
  {
    category: "Tree",
    title: "Diameter of a Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/diameter-of-a-binary-tree/",
  },
  {
    category: "Tree",
    title: "Lowest Common Ancestor (LCA)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/lowest-common-ancestor-binary-tree/",
  },
  {
    category: "Tree",
    title: "Burn a Binary Tree from Leaf",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/burn-the-binary-tree-starting-from-the-target-node/",
  },
  {
    category: "Tree",
    title: "Count Node in a Complete Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/count-number-of-nodes-in-a-complete-binary-tree/",
  },
  {
    category: "Tree",
    title: "Serialize and Deserialize a Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/serialize-and-deserialize-a-binary-tree/",
  },
  {
    category: "Binary Search Tree",
    title: "Background of BST",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-search-tree-data-structure/",
  },
  {
    category: "Binary Search Tree",
    title: "Introduction to BST",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-search-tree-data-structure/",
  },

  {
    category: "Binary Search Tree",
    title: "Search in BST",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-search-tree-set-1-search-and-insertion/",
  },
  {
    category: "Binary Search Tree",
    title: "Insertion in BST",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-search-tree-set-1-search-and-insertion/",
  },
  {
    category: "Binary Search Tree",
    title: "Deletion in BST",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-search-tree-set-2-delete/",
  },
  {
    category: "Binary Search Tree",
    title: "Floor in BST",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/floor-and-ceil-from-a-bst/",
  },
  {
    category: "Binary Search Tree",
    title: "Ceil in BST",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/floor-and-ceil-from-a-bst/",
  },
  {
    category: "Binary Search Tree",
    title: "Self Balancing BST",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/balanced-binary-tree/",
  },
  {
    category: "Binary Search Tree",
    title: "AVL Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/avl-tree-set-1-insertion/",
  },
  {
    category: "Binary Search Tree",
    title: "Red Black Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/red-black-tree-set-1-introduction/",
  },
  {
    category: "Binary Search Tree",
    title: "Applications of Self Balancing BST",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/inversion-count-in-array-using-self-balancing-bst/",
  },
  {
    category: "Binary Search Tree",
    title: "set in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/set-in-cpp-stl/",
  },
  {
    category: "Binary Search Tree",
    title: "map in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/map-associative-containers-the-c-standard-template-library-stl/",
  },
  {
    category: "Binary Search Tree",
    title: "Ceiling on Left Side",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/ceiling-on-left-side-of-an-array/",
  },
  {
    category: "Binary Search Tree",
    title: "Find kth smallest in BST",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/kth-smallest-element-in-bst/",
  },
  {
    category: "Binary Search Tree",
    title: "Check for BST",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/check-if-a-given-binary-tree-is-binary-search-tree/",
  },
  {
    category: "Binary Search Tree",
    title: "Fix a BST with two nodes swapped",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/fix-two-swapped-nodes-of-bst/",
  },
  {
    category: "Binary Search Tree",
    title: "Pair with given sum in BST",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-a-pair-with-given-sum-in-bst/",
  },
  {
    category: "Binary Search Tree",
    title: "Vertical Sum in Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/vertical-sum-of-a-binary-tree/",
  },
  {
    category: "Binary Search Tree",
    title: "Vertical Traversal of Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/vertical-order-traversal-of-binary-tree/",
  },
  {
    category: "Binary Search Tree",
    title: "Top View of Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/print-nodes-top-view-binary-tree/",
  },
  {
    category: "Binary Search Tree",
    title: "Bottom View of Binary Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/bottom-view-binary-tree/",
  },
  {
    category: "Heap",
    title: "Binary Heap Introduction",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/binary-heap/",
  },
  {
    category: "Heap",
    title: "Binary Heap Implementation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/binary-heap/",
  },
  {
    category: "Heap",
    title: "Binary Heap Insert",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/insertion-and-deletion-in-heaps/",
  },
  {
    category: "Heap",
    title: "Heapify and Extract Min",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/building-heap-from-array-and-extracting-min/",
  },
  {
    category: "Heap",
    title: "Decrease key, delete and build heap",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/decrease-key-delete-and-build-heap-operations/",
  },
  {
    category: "Heap",
    title: "priority_queue in C++",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/priority-queue-in-cpp-stl/",
  },
  {
    category: "Heap",
    title: "Sort a K-sorted Array",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/sort-nearly-sorted-array-using-min-heap/",
  },
  {
    category: "Heap",
    title: "Purchasing Maximum Items",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/maximize-array-sum-after-k-negations/",
  },
  {
    category: "Heap",
    title: "K Largest Elements",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/k-largest-elements-in-an-array/",
  },
  {
    category: "Heap",
    title: "K Closest Elements",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-k-closest-elements-given-value/",
  },
  {
    category: "Heap",
    title: "Merge K Sorted Arrays",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/merge-k-sorted-arrays/",
  },
  {
    category: "Heap",
    title: "Median of a Stream",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/median-of-stream-of-integers-running-integers/",
  },
  {
    category: "Graph",
    title: "Introduction to Graph",
    type: "Question",
    url: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/",
  },
  {
    category: "Graph",
    title: "Graph Representation (Adjacency Matrix)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/graph-and-its-representations/",
  },
  {
    category: "Graph",
    title: "Graph Representation (Adjacency List)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/graph-and-its-representations/",
  },
  {
    category: "Graph",
    title: "Adjacency Matrix v/s Adjacency List",
    type: "Question",
    url: "https://www.geeksforgeeks.org/difference-between-adjacency-list-and-adjacency-matrix/",
  },
  {
    category: "Graph",
    title: "Breadth First Search (BFS)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/breadth-first-search-or-bfs-for-a-graph/",
  },
  {
    category: "Graph",
    title: "Applications of BFS",
    type: "Question",
    url: "https://www.geeksforgeeks.org/applications-of-breadth-first-search/",
  },
  {
    category: "Graph",
    title: "Depth First Search (DFS)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/depth-first-search-or-dfs-for-a-graph/",
  },
  {
    category: "Graph",
    title: "Applications of DFS",
    type: "Question",
    url: "https://www.geeksforgeeks.org/applications-of-depth-first-search/",
  },
  {
    category: "Graph",
    title: "Shortest Path in an Unweighted Graph",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/shortest-path-unweighted-graph/",
  },
  {
    category: "Graph",
    title: "Detect Cycle in an Undirected Graph",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/detect-cycle-in-an-undirected-graph/",
  },
  {
    category: "Graph",
    title: "Detect Cycle in a Directed Graphs (Part 1)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/detect-cycle-in-a-directed-graph-using-indegree/",
  },
  {
    category: "Graph",
    title: "Topological Sort (Kahn's BFS based algorithm)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/topological-sorting-indegree-algo/",
  },
  {
    category: "Graph",
    title: "Detect Cycle in a Directed Graphs (Part 2)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/detect-cycle-in-a-directed-graph-using-dfs/",
  },
  {
    category: "Graph",
    title: "Topological Sort (DFS based algorithm)",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/topological-sorting-dfs-algo/",
  },
  {
    category: "Graph",
    title: "Shortest Path in a DAG",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/shortest-path-in-a-directed-acyclic-graph/",
  },
  {
    category: "Graph",
    title: "Prim's Algorithm/Minimum Spanning Tree",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/prims-minimum-spanning-tree-mst-greedy-algo/",
  },
  {
    category: "Graph",
    title: "Implementation of Prim's Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/prims-algorithm-using-priority-queue-stl/",
  },
  {
    category: "Graph",
    title: "Dijkstra's Shortest Path Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/dijkstras-shortest-path-algorithm-greedy/",
  },
  {
    category: "Graph",
    title: "Implementation of Dijkstra's Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/dijkstras-shortest-path-algorithm-using-priority_queue-stl/",
  },
  {
    category: "Graph",
    title: "Kosaraju's Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/strongly-connected-components-kosarajus-algorithm/",
  },
  {
    category: "Graph",
    title: "Bellman Ford Shortest Path Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/bellman-ford-algorithm-dp-23/",
  },
  {
    category: "Graph",
    title: "Articulation Points",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/articulation-points-or-cut-vertices-in-a-graph/",
  },
  {
    category: "Graph",
    title: "Bridges in a Graph",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/bridge-in-a-graph/",
  },
  {
    category: "Graph",
    title: "Tarjan's Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/tarjan-algorithm-find-strongly-connected-components/",
  },
  {
    category: "Graph",
    title: "Kruskal's Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/kruskals-algorithm-minimum-spanning-tree-set-2/",
  },
  {
    category: "Greedy",
    title: "Introduction to Greedy Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/greedy-algorithms/",
  },
  {
    category: "Greedy",
    title: "Applications of Greedy Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/applications-of-greedy-algorithm/",
  },
  {
    category: "Greedy",
    title: "Activity Selection Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/activity-selection-problem-greedy-algo/",
  },
  {
    category: "Greedy",
    title: "Fractional Knapsack Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/fractional-knapsack-problem/",
  },
  {
    category: "Greedy",
    title: "Job Sequencing Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/job-sequencing-problem/",
  },
  {
    category: "Greedy",
    title: "Huffman Coding",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/huffman-coding-greedy-algo/",
  },
  {
    category: "Backtracking",
    title: "Concepts of Backtracking",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/backtracking-introduction/",
  },
  {
    category: "Backtracking",
    title: "Rat in a Maze",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/rat-in-a-maze-backtracking-2/",
  },
  {
    category: "Backtracking",
    title: "N Queen Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/n-queen-problem-backtracking-3/",
  },
  {
    category: "Backtracking",
    title: "Sudoku Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/sudoku-backtracking-7/",
  },
  {
    category: "Dynamic Programming",
    title: "Introduction to Dynamic Programming",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/introduction-to-dynamic-programming-data-structures-and-algorithm-tutorials/",
  },
  {
    category: "Dynamic Programming",
    title: "Applications of Dynamic Programming",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/dynamic-programming-meaning-in-dsa/",
  },
  {
    category: "Dynamic Programming",
    title: "Dynamic Programming Memoization",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/what-is-memoization-a-complete-tutorial/",
  },
  {
    category: "Dynamic Programming",
    title: "Dynamic Programming Tabulation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/tabulation-vs-memoization/",
  },
  {
    category: "Dynamic Programming",
    title: "Longest Common Subsequence",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/longest-common-subsequence-dp-4/",
  },
  {
    category: "Dynamic Programming",
    title: "Variation of LCS",
    type: "Question",
    url: "https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/",
  },
  {
    category: "Dynamic Programming",
    title: "Coin Change",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/coin-change-dp-7/",
  },
  {
    category: "Dynamic Programming",
    title: "Edit Distance",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/edit-distance-dp-5/",
  },
  {
    category: "Dynamic Programming",
    title: "Longest Increasing Subsequence",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/longest-increasing-subsequence-dp-3/",
  },
  {
    category: "Dynamic Programming",
    title: "Variation of LIS",
    type: "Question",
    url: "https://www.geeksforgeeks.org/longest-increasing-subsequence-dp-3/",
  },
  {
    category: "Dynamic Programming",
    title: "Maximum Cuts",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/maximize-number-of-segments-of-length-p-q-r/",
  },
  {
    category: "Dynamic Programming",
    title: "Minimum coins to make a value",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/find-minimum-number-of-coins-that-make-a-change/",
  },
  {
    category: "Dynamic Programming",
    title: "Minimum Jumps to Reach End",
    type: "Question",
    url: "https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/",
  },
  {
    category: "Dynamic Programming",
    title: "0-1 Knapsack",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/0-1-knapsack-problem-dp-10/",
  },
  {
    category: "Dynamic Programming",
    title: "Optimal Strategy for a Game",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/optimal-strategy-for-a-game-dp-31/",
  },
  {
    category: "Dynamic Programming",
    title: "Egg Dropping Puzzle",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/egg-dropping-puzzle-dp-11/",
  },
  {
    category: "Dynamic Programming",
    title: "Count BSTs with n keys",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/program-nth-catalan-number/",
  },
  {
    category: "Dynamic Programming",
    title: "Maximum Sym with number two consecutives",
    type: "Question",
    url: "https://www.geeksforgeeks.org/maximum-sum-such-that-no-two-elements-are-adjacent/",
  },
  {
    category: "Dynamic Programming",
    title: "Subset Sum Problem",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/subset-sum-problem-dp-25/",
  },
  {
    category: "Dynamic Programming",
    title: "Matrix Chain Multiplcation",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/matrix-chain-multiplication-dp-8/",
  },
  {
    category: "Dynamic Programming",
    title: "Palindrome Partitioning",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/palindrome-partitioning-dp-17/",
  },
  {
    category: "Dynamic Programming",
    title: "Allocate Minimum Number of Pages",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/allocate-minimum-number-pages/",
  },
  {
    category: "Trie",
    title: "Trie Data Structure",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/trie-insert-and-search/",
  },
  {
    category: "Trie",
    title: "Trie Implementation",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/trie-delete/",
  },
  {
    category: "Trie",
    title: "Count Distinct Rows in a Binary Matrix",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/count-distinct-rows-in-a-binary-matrix-using-trie/",
  },
  {
    category: "Segment and Binary Indexed Tree",
    title: "Introduction to Segment Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/segment-tree-introduction/",
  },
  {
    category: "Segment and Binary Indexed Tree",
    title: "Constructing a Segment Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/segment-tree-set-1-sum-of-given-range/",
  },
  {
    category: "Segment and Binary Indexed Tree",
    title: "Range Query on a Segment Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/segment-tree-query/",
  },
  {
    category: "Segment and Binary Indexed Tree",
    title: "Update Query on a Segment Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/segment-tree-set-2-range-minimum-query/",
  },
  {
    category: "Segment and Binary Indexed Tree",
    title: "Introduction to Binary Indexed Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-indexed-tree-or-fenwick-tree-2/",
  },
  {
    category: "Segment and Binary Indexed Tree",
    title: "Prefix Sum on a Binary Indexed Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-indexed-tree-or-fenwick-tree-2/",
  },
  {
    category: "Segment and Binary Indexed Tree",
    title: "Update Query on a Binary Indexed Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-indexed-tree-or-fenwick-tree-2/",
  },
  {
    category: "Segment and Binary Indexed Tree",
    title: "Constructing a Binary Indexed Tree",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/binary-indexed-tree-or-fenwick-tree-2/",
  },
  {
    category: "Disjoint Set",
    title: "Introduction to Disjoint Set",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/disjoint-set-data-structures/",
  },
  {
    category: "Disjoint Set",
    title: "Find and Union operations on Disjoint Set",
    type: "Explanation",
    url: "https://www.geeksforgeeks.org/dsa/disjoint-set-union-find/",
  },
  {
    category: "Disjoint Set",
    title: "Union by Rank",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/union-by-rank-path-compression/",
  },
  {
    category: "Disjoint Set",
    title: "Path Compression",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/union-by-rank-path-compression/",
  },
  {
    category: "Disjoint Set",
    title: "Kruskal's Algorithm",
    type: "Question",
    url: "https://www.geeksforgeeks.org/dsa/kruskals-algorithm-minimum-spanning-tree-set-2/",
  },
];
